### ISSUE TITLE
"can't measure", "OFFLINE" messages on display, no measurements

### ISSUE THREAD

**Issue by mushroomjungl3** [electrical-pro/SmartBoard#11]
I got the message"can't measure" and "OFFLINE" on the display and i dont know what to do .

**Comment by mushroomjungl3** [comment]
Problem solved, I just had to swap tx and rx wires. Connection with router just took bit longer than I expected.

**Comment by ajguab-prog** [comment]
Hello i’m just beginning this project, can you help me and teach me how can i set up and upload the prepared code to the device
