### ISSUE TITLE
Temperature [ERROR] 

### ISSUE THREAD

**Issue by OZ-786** [electrical-pro/SmartBoard#3]
@electrical-pro I'm in need of your assistance .
I'm not getting reading from the temperature sensor, always on -127.0 degree Celsius

**Comment by Mis1ify** [comment]
Could you tell me what did you do to get this working? I have same issue.

**Comment by ajguab-prog** [comment]
Hello i’m just beginning this project, can you help me and teach me how can i set up and upload the prepared code to the device
